import { config } from "dotenv";
config();

export const APP_CONFIG = {
  PORT: process.env.PORT || 5003,
  MAIN_PATHS: {
    BLOGS: "/blogs",
    POSTS: "/posts",
    TESTS: "/testing",
    USERS: "/users",
    AUTH: "/auth",
    COMMENTS: "/comments",
    SECURITY: "/security",
  },
  ENDPOINT_PATHS: {
    AUTH: {
      LOGIN: "/login",
      LOGOUT: "/logout",
      PASSWORD_RECOVERY: "/password-recovery",
      CONFIRM_PASSWORD_RECOVERY: "/new-password",
      REFRESH_TOKEN: "/refresh-token",
      REGISTRATION: "/registration",
      REGISTRATION_CONFIRMATION: "/registration-confirmation",
      REGISTRATION_EMAIL_RESENDING: "/registration-email-resending",
      ME: "/me",
    },
  },
  TEST_PATHS: {
    DEVICES: "/security/devices",
    REFRESH_TOKEN: "/auth/refresh-token",
    LOGOUT: "/auth/logout",
  },
  ADMIN: process.env.ADMIN || "admin:qwerty",
  MONGO_URL: process.env.MONGO_URL || "mongodb://localhost:27017",
  DB_NAME: process.env.DB_NAME as string,
  TEST_DB_NAME: "test-db",
  COLLECTIONS: {
    BLOGS_COLLECTION_NAME: "blogs",
    POSTS_COLLECTION_NAME: "posts",
    USERS_COLLECTION_NAME: "users",
    COMMENTS_COLLECTION_NAME: "comments",
    SESSIONS_COLLECTION_NAME: "sessions",
    APICALLS_COLLECTION_NAME: "apicalls",
  },
  JWT_SECRET_ACCESS: process.env.JWT_SECRET_ACCESS as string,
  JWT_SECRET_REFRESH: process.env.JWT_SECRET_REFRESH as string,
  REFRESH_TOKEN_COOKIE_NAME: "refreshToken",
  NODEMAILER_USERNAME: process.env.NODEMAILER_USERNAME,
  NODEMAILER_PASS: process.env.NODEMAILER_PASS,
  NODEMAILER_MAIL_SERVICE: process.env.NODEMAILER_MAIL_SERVICE,
  REFRESH_TOKEN_TTL: 20,
  ACCESS_TOKEN_TTL: 10,
  REQUEST_LIMIT: 5,
  REQUEST_LIMIT_PERIOD: 10,
  USER_LOGINS_TEST_COUNT: 4,
  ERROR_MESSAGES: {
    USER_NOT_FOUND: "User is not found",
    RECOVERY_CODE_IS_EXPIRED: "Recovery code is expired",
    RECOVERY_CODE_IS_INCORRECT: "Recovery code is incorrect",
  },
};
